### ISSUE TITLE
Swipe from edge?

### ISSUE THREAD

**Issue by geoguide** [dogfessional/react-swipeable#104]
Is there a way to do this included in this library? What I want to do is make it so that a swipe that comes from the edge of the screen opens a menu. I'm not sure if this is possible, and have been trying to figure out a way to do it with onSwipedLeft etc.

**Comment by hartzis** [comment]
@geoguide if the swipe doesn't originate/start from within the `<Swipeable>` container `<div>` element then there is no way to track it.

I could see the posibility of tracking "swipes" on the body possibly via `document.body.addEventListener('touchmove', trackTouchMove, false)`
and 
`document.body.addEventListener('touchend', trackTouchEnd, false)`
```
const trackTouchMoveState = {};
function trackTouchMove (e) {
  // determine if swiping left from previous trackTouchMoveState
}
function trackTouchEnd () {
  // reset tracking state
  trackTouchMoveState = {}
}
```

just some thoughts
