### ISSUE TITLE
Request: Add gzipped size of the package to readme

### ISSUE THREAD

**Issue by Abisar** [dogfessional/react-swipeable#105]

**Comment by hartzis** [comment]
try:

http://img.badgesize.io/https://unpkg.com/react-swipeable/lib/Swipeable.js?compression=gzip&label=gzip%20size

**Comment by hartzis** [comment]
<img src="https://img.badgesize.io/https://unpkg.com/react-values/dist/react-values.min.js?compression=gzip&amp;label=react--values">
