### ISSUE TITLE
preventDefault prevents vertical scrolling

### ISSUE THREAD

**Issue by zeemawn** [dogfessional/react-swipeable#106]
Regarding this commit: https://github.com/dogfessional/react-swipeable/commit/f576b975c24aa945781f30341214ca6c794a9366

I'm implementing a list with vertically aligned items. On mobile devices, scrolling through this list is not possible, because the scroll-event gets ignored through preventDefault.

Is there a way to solve this?

**Comment by hartzis** [comment]
@zeemawn did this break after that commit by chance?

would you happen to have an example repo or [codesandbox.io](https://codesandbox.io/s/qq7759m3lq?module=%2Fsrc%2FCarousel.js) to share?

Few other questions:
- if it is a simple list of scrollable items could it just be handled with CSS?
- does just setting `preventDefaultTouchmoveEvent={false}` work? (probably already tried)

**Comment by 0rsa** [comment]
Same issue here.
It's impossible to scroll the page up and/or down with:
<Swipeable
                  onSwipingLeft={this.swipingLeft}
                  onSwipingRight={this.swipingRight}
                  trackMouse
                  preventDefaultTouchmoveEvent={false}>

I tried to double wrap <Swipeable> <Swipeable> as explained here: https://github.com/dogfessional/react-swipeable/issues/94

It doesn't work.

**Comment by hartzis** [comment]
- @0rsa do you have an example project/codesandbox i can use to help diagnose? I'm flying blind here.
- @0rsa did your application stop working when `v4.2.2` was released?

I really want to help you guys but i don't know exactly what is happening without having an example, anything, to actually test it.
