### ISSUE TITLE
'mousedown' event

### ISSUE THREAD

**Issue by akhegai** [dogfessional/react-swipeable#109]
Is it possible to provide both 'mouseup' and 'mousedown' events to the onSwiped callback?

**Comment by hartzis** [comment]
Absolutely!

`react-swipeable` only attaches an `onMouseDown` to the wrapping div, but it will also fire a passed in `onMouseDown`.

As for `onMouseUp` it will the be spread onto the wrapping div and work like normal.

so this should work:
```
onMouseDown = (e) => { console.log('onMouseDown', e) }
onMouseUp = (e) => { console.log('onMouseUp', e) }

render() {
  return (
    <Swipeable 
      onMouseDown={onMouseDown}
      onMouseUp={onMouseUp}
    />
)}
```

**Comment by hartzis** [comment]
if you can't get the above to work, please create a codesandbox.io example and share it. I'd be happy to help!

You can start with this [codesandbox.io example](https://codesandbox.io/s/qq7759m3lq?module=%2Fsrc%2FCarousel.js)
