### ISSUE TITLE
Render props API

### ISSUE THREAD

**Issue by jedwards1211** [dogfessional/react-swipeable#111]
The way `Swipeable` renders an element is a bit difficult to work with.  I wish it would just call a child function with all of the event listeners I need to pass to the component I render, like the following.  Would you be open to a PR for this?

```js
<Swipeable onSwipedLeft={...}>
  {props => (
     <MyComplexComponent {...props}>
       <Child1 />
       <Child2 />
     </MyComplexComponent>
   )}
</Swipeable>
```

**Comment by jedwards1211** [comment]
Actually let me think about this for awhile.  The new react hooks API might provide a simpler way to do this.

**Comment by hartzis** [comment]
That would be an overhaul to this component, but I too have been contemplating ways to export the internals as hooks now. Let me know your thoughts.
