### ISSUE TITLE
add typescript types?

### ISSUE THREAD

**Issue by hartzis** [dogfessional/react-swipeable#125]
- [x] create / export types for typescript for v5
  - [x] types for `<Swipeable />` #133 
  - [x] types for `useSwipeable` #137 

- v4 types - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-swipeable/index.d.ts

**Comment by on3al** [comment]
Looks like definitely typed project exists, but the types don't map up correctly 👍 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-swipeable/index.d.ts

**Comment by hartzis** [comment]
@on3al awesome, thanks.

yeah, that looks like the v4 api. I updated the issue above for v5.

**Comment by hartzis** [comment]
Thank you @adambowles ! published #133 's types for `<Swipeable/>` as `react-swipeable@5.2.0-alpha.0`, could you check it out and verify the type additions are working?

Do you know how we deprecate the `DefinitelyTyped` definitions?

I'm going to attempt to create some types for `useSwipeable` and tests then we can get `5.2.0` out with both types.

**Comment by adambowles** [comment]
Yep, works perfectly!

I think we should leave DefinitelyTyped up for people to get types for v4 (if they're still depending on that version for whatever reason), maybe move it into a folder to indicate this (see https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node). I'm not very familiar with this process. Maybe we don't do anything at all.

**Comment by adambowles** [comment]
@hartzis https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

**Comment by hartzis** [comment]
Going to publish these with the bug fix #138 . 

All types currently published as `react-swipeable@5.2.0-alpha.3`.

**Comment by hartzis** [comment]
published with `5.2.0`, thank you again @adambowles !
