### ISSUE TITLE
useSwipeable does not refresh callbacks

### ISSUE THREAD

**Issue by caesarsol** [dogfessional/react-swipeable#136]
### Describe the bug
It seems that `useSwipable` does not refresh the handlers on subsequent renders.
It appears that the handlers used are the first ones with which the function is called.

Maybe it would need a `dependency` array, like `useImperativeHandle`?

(If this behaviour is expected, we should maybe write a description in the README)

### Steps or Sandbox to reproduce
https://codesandbox.io/s/p9n13oo0x

Try to swipe two times in the red area, the Page number does not update as expected.
In the green area it works, because we are calling the handlers inside a `setTimeout()` with closured value of the `page` variable.

### Device/Browser
All.

**Comment by bas-l** [comment]
I have the same issue. Upon swiping I do a callback that updates a prop in the parent, and the prop is updated in the render function, but not in the handler.

**Comment by hartzis** [comment]
@caesarsol Thank you for the issue and the example, incredibly helpful being able to reproduce.

Great question about if this is expected or not. I'm intrigued by the `useImperativeHandle` and may be related to my issue #134 .

@bas-l I do think it is related to #135 too, but that is for the component, `<Swipeable/>`, specifically and not the hook.

I'm going to dig a bit more into this. And please let me know if you think you have a solution or thoughts on if this should or shouldn't be expected.

**Comment by hartzis** [comment]
@caesarsol @bas-l @stephencookdev It is late, but i may have solved it? It may not be elegant but i think it works. #138 published as `react-swipeable@5.2.0-alpha.1`

@caesarsol I forked your codesandbox, again **THANK YOU**, and with `5.2.0-alpha.1` it appears to be working, https://codesandbox.io/s/9oy62kp0xr

**Comment by hartzis** [comment]
@bas-l I just merged #137 , funny i just made that last night too.

I just cut another alpha, `react-swipeable@5.2.0-alpha.3` that includes the `useSwipeable` types.

**Comment by caesarsol** [comment]
Hi @hartzis, thanks for the very quick response and fix!!

Very happy to have been useful. :)

**Comment by bas-l** [comment]
Now running 5.2.0-alpha.4 and everything seems to run well. Thanks @hartzis!

**Comment by hartzis** [comment]
fix published with `5.2.0` thank you @caesarsol and @bas-l !
