### ISSUE TITLE
Bug on demo site

### ISSUE THREAD

**Issue by robwold** [dogfessional/react-swipeable#146]
**Describe the bug**
I'm not seeing any console output when I swipe on the Feature Test Console on your demo site, either in 'components' or 'hooks'.

**Steps or Sandbox to reproduce**
Your demo feature console: http://dogfessional.github.io/react-swipeable/#FeatureTestConsole

**Expected behavior**
Some sort of visible effect or logging to the console, as per the description.

** Device/Browser **
I'm using Chrome Version 74.0.3729.157

**Comment by hartzis** [comment]
@robwold Hey, apologies for the late response. I am seeing the console output with dev tools open.

You have to turn on `trackMouse` prop to get the console output doing swipes with your mouse **or** `toggle device toolbar` in the dev tools to then mimic a touch device.

<img width="1224" alt="Screen Shot 2019-06-15 at 2 49 21 PM" src="https://user-images.githubusercontent.com/5378707/59556267-e90a6500-8f7c-11e9-8af8-2092e5e9b47b.png">

Let me know if this works for you.
