### ISSUE TITLE
Nested swipeable surfaces

### ISSUE THREAD

**Issue by arcanis** [dogfessional/react-swipeable#147]
I'm working on a "tabs within tabs" scenario, and from my first observations it seems as if the swipe events are triggered on both levels of tabs instead of the deepest only (note that the ideal would be for the deepest swipeable surface to have something like stopPropagation, so that it could decide whether the parent should access the events or not, for example to allow it to swipe left when the child can't anymore).

Is it something supported by `react-swipeable`?

**Comment by arcanis** [comment]
Found the answer by reading the source 🙂 It might at least be a good FAQ!

The easiest way is to call `stopPropagation` via the `onSwiping` handler - this will prevent the parent from receiving the `move` event, which will prevent it from detecting the swipe.

Additionally, the `dir` parameter from `onSwiping` contains the general direction of the swipe, so you can check that and decide whether to call `stopPropagation` or not based on some logic (for example if you've reached the edges of the swipeable surface).

**Comment by hartzis** [comment]
@arcanis Thank you for the issue and the answer! This is definitely really good info!

I also like the idea of creating a `FAQ` for `react-swipeable`.
