### ISSUE TITLE
Provide deltas relative to initial onTouchStart in onSwiping callback

### ISSUE THREAD

**Issue by samanpwbb** [dogfessional/react-swipeable#160]
Right now, a single swipe will return multiple `onSwiping` calls. In the app I'm building, I'm using deltaX and deltaY to show immediate feedback as user is swiping, but I don't want the deltas from every sub-event to accumulate. I wrote some code that looks like this:

```js
let firstInitial = [];
let prevX = null;
let prevY = null;

swiping = swipeData => {
  const { deltaX, deltaY, initial } = swipeData;
  let nextY = 0,
    nextX = 0;

  // New initial value, which mean a new swipe started.
  if (!_.isEqual(firstInitial, initial) {
    firstInitial = initial;
    prevX = 0;
    prevY = 0;
  } else {
    nextX = deltaX - prevX;
    nextY = deltaY - prevY;
    prevX = deltaX;
    prevY = deltaY;
  }
  // ...use nextY and nextX in an updater function
}
```

It'd be nice if I didn't have to write this code: 

- Best: `onSwiping` could provide deltas relative to start of the swipe in addition to providing full deltas for each onSwiping event as it does now.
- Still helpful: `onSwiping` could include an `initialEvent` so implementers could then more easily make deltas relative.

**Comment by hartzis** [comment]
Hey @samanpwbb, thanks for posting an issue with some ideas.

I think i'm having a hard time trying to understand exactly what you're looking for.

---
> `onSwiping` could provide deltas relative to start of the swipe
- Currently `deltaX` and `deltaY` on the `eventData` for `onSwiping` returns the delta from the intial x and initial y
  - https://github.com/dogfessional/react-swipeable#event-data
https://github.com/dogfessional/react-swipeable/blob/f79c308bb226fe4d091ed308c4bd246e774f710c/src/index.js#L78-L79
- Do you want the delta(s) from the __previous__ `onSwiping` in the __next__ `onSwiping`?
---
> `onSwiping` could include an `initialEvent`
- Can you explain what `initialEvent` would contain?
  - Would it just be the __first__ `eventData` object for the __first__ `onSwiping` triggered?

---

We can also try and help clean this code up a bit.
```
  // New initial value, which mean a new swipe started.
  if (!_.isEqual(firstInitial, initial) {
```
By introducing a `first` boolean? That would be `true` when it's the first event.

---
I'm absolutely open to taking a look at and considering a PR for what you're looking for and/or I can try and create a PR if we can clarify these a bit more.

Cheers!

**Comment by samanpwbb** [comment]
Thanks for getting back to me!

> Do you want the delta(s) from the previous onSwiping in the next onSwiping

After fiddling with my code a bit, I realize that it's necessary to throttle the onSwiping events, so deltas from previous events wouldn't help me unless react-swipeable did the throttling internally. It'd be awesome if it did, but that really expands the scope of this feature request 😄.

Your last next suggestion is my favorite:

> By introducing a first boolean? That would be true when it's the first event.

I think we could close this issue if just this feature was added. I'll try to find the time to put up a PR for you.

**Comment by hartzis** [comment]
Closing with #162
