### ISSUE TITLE
Fix React 16.9+ warnings to be ready for React 17

### ISSUE THREAD

**Issue by Ethorsen** [dogfessional/react-swipeable#165]
**Describe the bug**
This is not a bug, but simply a reminder to get prepared for React 17

**Steps or Sandbox to reproduce**
Any usage in React 16.9 +
![image](https://user-images.githubusercontent.com/1493968/66158526-0f1f4800-e5f4-11e9-9754-6f2612e5e06b.png)

**Expected behavior**
No warnings

** Device/Browser **
All

**Comment by hartzis** [comment]
@Ethorsen Thanks for the reminder.

I can't find any instance of `componentWillReceiveProps` in `react-swipeable` master branch.

What version are you using? If older than v5, I'd recommend updating to v5.

**Comment by denvaar** [comment]
@Ethorsen maybe that's coming from https://github.com/oliviertassinari/react-swipeable-views

**Comment by Ethorsen** [comment]
Ha, yes sry I hit the wrong library.  

My bad
