### ISSUE TITLE
onSwiped... events not fired

### ISSUE THREAD

**Issue by lordakshaya** [dogfessional/react-swipeable#21]
Hi,

I am using the npm v3.0.2 of this module. While it works on most devices e.g. iPhone 5, 5s, 6 and many android phones, there's a particular device I have found on which the onSwiped family of events arent firing. The phone model is Samsung Galaxy J1 Ace with Android v4.4 installed on it.

On further debugging, I observed the issue was caused cuz of `onTouchEnd` event not getting fired at end of a swipe gesture. I also observed that `onTouchEnd` event, **was** getting fired if I just did a TAP. On google around, I found some devs mentioning to call **e.preventDefault()** to be invoked in `touchStart` or `touchMove` events. But, I see thats not happening in this library.

Can you please see whats going on? And let me know about how to fix this?

Thanks!

**Comment by Bogdaan** [comment]
+1 onSwiped not fired

**Comment by hartzis** [comment]
@lordakshaya It does look like **e.preventDefault()** is being called in `touchMove` [here](https://github.com/dogfessional/react-swipeable/blob/master/jsx/Swipeable.jsx#L110).

We now have an [example app](http://dogfessional.github.io/react-swipeable/) working with the latest version 3.1.0, please let us know if it is still happening.

**Comment by fruitkiwi** [comment]
onSwipedLeft and onSwipedRight are fired only if also onSwipingLeft and onSwipingRight are set
on Android 4.x

**Comment by hartzis** [comment]
@fruitkiwi i see what you are saying. It seems we need to figure out the best way to trigger `e.preventDefault()` for most solutions, but I don't think firing it all the time is the answer.

I don't know the best solution, open to ideas. @goatslacker 

Ideas: 
* prop of `preventDefault` that has a default, `true` or `false` and either always prevents or not?
* Maybe a useragent check, but that seems dirty.

also related to #28, #27.

related info links:
* https://forum.jquery.com/topic/switching-e-preventdefault-on-and-off-so-swipe-works-on-android
* https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars&groupby=&sort=&id=4549
* https://github.com/hammerjs/hammer.js/issues/366
* http://stackoverflow.com/questions/7691551/touchend-event-in-ios-webkit-not-firing

**Comment by ChrisRus** [comment]
Looks like some effort to address this on fork https://github.com/abilashs90/react-swipeable/commits/master :: I'm wandering in to try to re-use this code and pass back changes that I think would be generally useful. Thanks for the effort here @hartzis.

**Comment by hartzis** [comment]
#37 has a fix for the onSwiped[direction]'s

**Comment by hartzis** [comment]
I'm hoping #37 fixes this issue, please let me know if it still exists.
