### ISSUE TITLE
Container element should be configurable

### ISSUE THREAD

**Issue by nuthinking** [dogfessional/react-swipeable#24]
react-swiper had tagName for instance. I am pretty new to React I could implement it in the .js, not sure how to do it in the ,jsx

**Comment by hartzis** [comment]
I took a look at [react-swiper](https://github.com/joakimbeng/react-swiper/blob/master/src/Swiper.jsx#L10), but I'm having trouble contemplating a use case where this is actually useful.

**Comment by nuthinking** [comment]
In my case, I had a list of <li> and wanted each item to be swipe-able.

**Comment by serheyShmyg** [comment]
@nuthinking You can wrap content of your li into swipeable.

**Comment by jcperez-ch** [comment]
@hartzis I believe what @nuthinking stated is a valid use case, where we should allow the user to configure the element so they can rely on existing css if the want to, instead of changing the css in fuction of this always present div.

Not a big deal for many, but a huge one for others.

**Comment by hartzis** [comment]
This seems reasonable, as long as the default stays 'div'.

**Comment by pixelbreaker** [comment]
+1

This is how `react-tappable` handles it, you can pass a `component` prop to it. Makes it much more flexible in different use cases.

**Comment by hartzis** [comment]
Add `nodeName` prop with PR #40 to allow container to be configurable.
