### ISSUE TITLE
An example would be nice

### ISSUE THREAD

**Issue by nuthinking** [dogfessional/react-swipeable#25]
Especially to show what would be the best approach to move the element, have hint beneath etc..

**Comment by hartzis** [comment]
Going to start working on a couple examples today. Hopefully have something posted to the gh-pages branch soon.

#18 - docs

**Comment by hartzis** [comment]
@nuthinking tell me what you think, http://dogfessional.github.io/react-swipeable/

**Comment by nuthinking** [comment]
Looks good, thanks!
