### ISSUE TITLE
Touch end not firing on certain devices

### ISSUE THREAD

**Issue by abilashs90** [dogfessional/react-swipeable#27]
I'm was testing on Redmi 1s and `touchend` is not fired because some browsers tend to fire `touchcancel` before touchend.

Here is more info:

http://stackoverflow.com/questions/7691551/touchend-event-in-ios-webkit-not-firing

Any workarounds for this?

**Comment by hartzis** [comment]
seems related to #21 , closing this ticket and will track there. we need to discover the best solution for when to fire `e.preventDefault()`
