### ISSUE TITLE
cancel swipe depending on the return of onSwiping* callbacks

### ISSUE THREAD

**Issue by MoOx** [dogfessional/react-swipeable#28]
That might help me to implement a pull to refresh only when I am swiping at the top of my container. I would be able to detect if the container is at its top and return true/false if not which might trigger the scroll or not. Currently I use onSwipingDown but it's blocking the scroll up :)

**Comment by MoOx** [comment]
It's easy

```diff
        if (this.props.onSwipingDown) {
-          this.props.onSwipingDown(e, pos.absY)
-          cancelPageSwipe = true
+          cancelPageSwipe = this.props.onSwipingDown(e, pos.absY)
        }

//...

-    if (cancelPageSwipe) {
+    if (cancelPageSwipe === undefined || cancelPageSwipe) {
      e.preventDefault()
    }
```

With this diff, no breaking change and you can control from onSwipingDown if you want to prevent default or not.
Can be make for all onSwiping* too.
Are you open for this change?

**Comment by MoOx** [comment]
Are you open for this (tiny but very cool) change?

**Comment by hartzis** [comment]
Personally I do think it is interesting and neat hack. Just wondering if it could be made more explicit because `if (cancelPageSwipe === undefined || cancelPageSwipe)` doesn't look/feel right.

It also seems it would be a major version bump. Users could randomly be returning values from their callbacks of `onSwiping`'s.

@goatslacker thoughts on this?

**Comment by MoOx** [comment]
The `(cancelPageSwipe === undefined || cancelPageSwipe)` was to avoid breaking changes, but you are right, that might introduce some changes anyway.
So if that's a breaking change, we can assume that onSwiping* must return a boolean.
Or we can reverse the thing: `noCancelPageSwipe = this.props.onSwipingDown(e, pos.absY)` (return undefined or false => no preventDefault, return true: preventDefault.
Hum so, noCancelPageSwipe will be a preventDefault flag.

**Comment by hartzis** [comment]
this seems very much related to a bigger issue with #21, and androids and old ios. any ideas for #21?
