### ISSUE TITLE
peerDependencies need to be fixed

### ISSUE THREAD

**Issue by molson504x** [dogfessional/react-swipeable#35]
In the latest version, you added the follownig peerDependency:

`"react": "^0.12.0 || ^15.0.0-0"`

I've got react 0.13.3 in my project, and I get NPM warnings that 0.13.3 isn't compatible with that dependency, probably because of the carat notation since 0.13.3 would probably be invalid with ^0.12.0.  I think this needs to be `>=0.12.0 || ^15.0.0-0`

**Comment by hartzis** [comment]
nice catch and thank you! btw great site -> http://semver.npmjs.com/

**Comment by hartzis** [comment]
fixed with 3.3.1
