### ISSUE TITLE
What's wrong with peer deps?

### ISSUE THREAD

**Issue by voronianski** [dogfessional/react-swipeable#4]
I have React `0.12.2` installed and now installing `react-swipeable`, getting the error:

```bash
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "react-swipeable" "--save"
```

**Comment by goatslacker** [comment]
Hmmm I'm not sure. Let me take a look

**Comment by hartzis** [comment]
So there is a ton of good discussion about peer dependencies. I think we may want to remove the peer dependency for react and just have it as a dev dependency.

Npm decision here, with links to other referenced packages:
https://github.com/npm/npm/issues/6565#issuecomment-74971689

From what I can tell it seems other libraries are moving towards just having react as a dev dependency.

References:
https://github.com/glenjamin/react-hotkey/commit/68510aa17850581de5958fc512ecc675f4572a44
https://github.com/rackt/react-router/blob/master/package.json

**Comment by goatslacker** [comment]
+1 to moving to devDep
