### ISSUE TITLE
Unknown prop warning

### ISSUE THREAD

**Issue by thebuilder** [dogfessional/react-swipeable#42]
The module is setting props on the div, causing warnings in React 15.2.0:
https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b

**Comment by thebuilder** [comment]
See: https://github.com/dogfessional/react-swipeable/pull/43

**Comment by serheyShmyg** [comment]
+1

**Comment by hartzis** [comment]
solved with #44
