### ISSUE TITLE
stopPropagation to prevent parent swipe

### ISSUE THREAD

**Issue by MikeLP** [dogfessional/react-swipeable#46]
Please add ability to call stopPropagation by props flag.

**Comment by MikeLP** [comment]
example 
`<Swipeable stopPropagation={true} ></Swipeable>`

In src:
` stopPropagation: React.PropTypes.bool`

and

`touchStart: function(e) {
if (this.props.stopPropagation) {
  e.stopPropagation()
}

...
}`

**Comment by hartzis** [comment]
Sounds good, going to set it up like `preventDefaultTouchmoveEvent`, so `stopPropagationTouchmoveEvent`.

**Comment by MikeLP** [comment]
Right. In my case I have swipeable "switch" component in swipeable sidebar. So when I try to swipe a "switch" - sidebar will be swiped too. So one of solutions it will be stopPropagation property. If you see another way to resolve this issue,  it's doesn't matter for me. Unfortunately for now I forced to manually change yours component and use separatly in my project instead of npm. It will be nice to have fast fix of this issue and rollback to npm.

P.S. Another case - try to make the stopPropagation method call from any onSwipe callback.

**Comment by hartzis** [comment]
@MikeLP added via #47, and published to npm as 3.6.0

**Comment by MikeLP** [comment]
Thanks.

**Comment by oleksandr-danylchenko** [comment]
This option was deleted? How it can be emulated now?

**Comment by hartzis** [comment]
@oleksandr-danylchenko yeah, in v5 we removed `stopPropagation`. In the migration docs we mention that you can call `e. stopPropagation()` when you need to via the onSwiping/Swiped callbacks.

https://github.com/FormidableLabs/react-swipeable/blob/master/migration.md#stoppropagation

Example:
```
const onSwiping = ( { event } ) => {
  event.stopPropagation();
}
const handlers = useSwipeable({ onSwiping })
return (<div {...handlers}> You can swipe here </div>)
```

**Comment by mauricioross** [comment]
Hello! When I try to scroll a Dropdown inside the element that contains the swipe handlers, it executes its actions, how can I stop it? Thanks for your time! 

PS: i try stopPropagation(). but is the same.

**Comment by hartzis** [comment]
@mauricioross Howdy. Without an example to work with i can only guess, but my best guess would be to try adding an onClick and/or onTouchStart/onTouchMove handlers to your Dropdown and call `e.preventDefault` ? 🤷 hopefully the event stops bubbling and doesn't get to the swipe handlers?
