### ISSUE TITLE
Pass ref to rendered element

### ISSUE THREAD

**Issue by lochstar** [dogfessional/react-swipeable#48]
I require access to the rendered element to determine it's width.

Attaching a `ref` to `<Swipable>` gives access to the component but not the underlying DOM node.

I can access the node via: `this.refs.swipable._reactInternalInstance._renderedComponent._hostNode`.
or
`ReactDOM.findDOMNode(this.refs.swipable)`

My problem can be solved if Swipable attaches it's own `ref` attribute. e..g

```javascript
var newProps = _extends({}, this.props, {
    ref="elem"
    onTouchStart: this.touchStart,
    onTouchMove: this.touchMove,
    onTouchEnd: this.touchEnd
});
```

Can now be accessed via: `this.refs.swipable.refs.elem`.

Thoughts?

**Comment by hartzis** [comment]
I like your solution with the `ReactDOM.findDOMNode(this.refs.swipeable)`, that's probably the best for now.

We eventually want to implement something like #36 where we attach the `react-swipeable` events to another element.

**Comment by lochstar** [comment]
Sounds like a good idea, cheers.
