### ISSUE TITLE
Not sending swipe events when swiping back close to original position

### ISSUE THREAD

**Issue by jkettmann** [dogfessional/react-swipeable#49]
First of all thanks for this nice library.

I'm using react-swipeable to swipe through a list of images horizontally. The images follow the movement of the swipe to have a nice animation. 

So when I'm starting to swipe for example to the left, the image starts moving to the left as well. When I go back close to the position of the touch start event **without lifting my finger**, the image follows up to the horizontal distance of the delta value (so 10px default). When I continue moving right, there is a small gap of 20px where the image doesn't follow the touch move.

The responsible [lines](https://github.com/dogfessional/react-swipeable/blob/master/src/Swipeable.js#L86) are:

```
if (pos.absX < this.props.delta && pos.absY < this.props.delta) {
    return
}
```

What if we check if swipe is ongoing and fire the corresponding events even though `pos.absX < this.props.delta` etc? So something like 

```
if (pos.absX < this.props.delta && pos.absY < this.props.delta && !this.state.swiping) {
    return
}
```

I could prepare a pull request for this

**Comment by hartzis** [comment]
goatslacker definitely did a great job with this library!

Thank you for the great right up, code lines, and example described, very helpful to understanding this problem. It is an interesting problem i haven't ran into yet, I'd love to add a small/light image carousel to the example page someday.

I do think your proposed solution would work, but just curious if just setting the `delta` to 0 "solves" this?

**Comment by jkettmann** [comment]
Thanks for the hint. Actually I didn't try that before and it works. I thought delta was important to distinguish swipe and click or something. 

Still setting delta to 0 seems a bit hacky to me. I think for implementing correct drag behaviour you would need to follow the touch movement back to its starting point and not stop shortly before that even though you might want to use a delta threshold anyways
