### ISSUE TITLE
Listen for mouse events as well?

### ISSUE THREAD

**Issue by jakepusateri** [dogfessional/react-swipeable#51]
Would it be possible to listen for mousedown, mousemove, and mouseup as well?

This would be useful when a device has touch capability but the user is using a mouse. (e.g. touch laptops like Surface Pro)

**Comment by hartzis** [comment]
@jakepusateri Thanks for the PR and I think this is an interesting issue especially with the bigger tablets out there.

Could you re-submit that PR but make it an opt-in via a prop?

**Comment by hartzis** [comment]
Thank you @jakepusateri and @Marcel-G, merged in #53
