### ISSUE TITLE
Chrome 56 and later, warning with preventDefault, react issue

### ISSUE THREAD

**Issue by MikeLP** [dogfessional/react-swipeable#54]
`SyntheticEvent.js:115 Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080`

Actually I don't know what is this. I will investigate.

**Comment by hartzis** [comment]
Any update on this? I too see this warning in the example but it doesn't appear to be 'bad'.

**Comment by hartzis** [comment]
closing to inactivity

**Comment by RByers** [comment]
As for the warning from Chrome: sorry for the trouble, this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention).  There's probably a missing `touch-action` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action), which is necessary to support touch on IE/Edge anyway.

**Comment by celsomtrindade** [comment]
I'm still getting this warning. Doesn't seem to stop anything from working. But everytime I swipe, the warning is appearing.

**Comment by hartzis** [comment]
React has discussion about this facebook/react#8968

**Comment by hartzis** [comment]
if you wish to turn off scrolling/zooming inside the `<Swipeable />` area you can pass a `style` prop to it with `touch-action: none`, https://developers.google.com/web/updates/2017/01/scrolling-intervention

`<Swipeable style={{touchAction: 'none'}} />`

**Comment by hartzis** [comment]
@MikeLP would you happen to have thoughts on #69 ?

proposing changing `preventDefault` prop to default to false in v4 because of this chrome change
