### ISSUE TITLE
"Up" and "Down" appear to be mixed up

### ISSUE THREAD

**Issue by epzilla** [dogfessional/react-swipeable#6]
On my iOS devices, I wasn't able to get `onSwipedDown` to respond to a swipe from the top of the element to the bottom, but instead it responded to swipes originating from the bottom of the element and ending at the top. So I switched the handler to `onSwipedUp` to try and get the functionality I was originally looking for, and it worked. I'm wondering if maybe it's a mix-up regarding the fact that the Y-coordinates increase going down the viewport, instead of up. I know that's tripped me up a few times.

**Comment by goatslacker** [comment]
Which version is this?

**Comment by epzilla** [comment]
Looks like 3.0.0

**Comment by goatslacker** [comment]
Ok I'll take a look. It just went through some changes so things might've gotten mixed up in the process

**Comment by hartzis** [comment]
@epzilla Thanks for catching this, when I added those I definitely seemed to have gotten mixed up with the y-coords.

**Comment by hartzis** [comment]
Fixed, @epzilla thank you for identifying and @goatslacker thanks for merging and bumping the version

**Comment by goatslacker** [comment]
It's been published as 3.0.1

**Comment by epzilla** [comment]
I just noticed that `onSwipingUp` and `onSwipingDown` are still mixed up as well. I've gone ahead and put in a PR for that one.
