### ISSUE TITLE
Swipe triggers continuously after reaching delta

### ISSUE THREAD

**Issue by farskid** [dogfessional/react-swipeable#60]
Consider the case where delta is set to `10px`. If user continues to swipe after that delta amount, swipe will be triggered relatively. This has to be fixed as it could turn out into a falsy feature.

**Comment by hartzis** [comment]
there is a react proptypes setup for delta, `delta: React.PropTypes.number`. If you give it a string react will warn you in dev mode.

But you are correct,
```javascript
1 < '10px' // false
1000 < '10px' // false
```
