### ISSUE TITLE
[Question] deltaX max and mininum value?

### ISSUE THREAD

**Issue by Kikobeats** [dogfessional/react-swipeable#62]
I'm trying to comine `onSwiping` and `onSwiped` method for open an aside left and aside right

![lol](https://cloud.githubusercontent.com/assets/2096101/22222583/bf12b0f6-e1b7-11e6-95da-d0559b58d4c5.png)

I represented as rectangule the are that I want to captue for reveal the aside and the arrow means the direction of the velocity.

Do you recommend me any tip for do it?

**Comment by hartzis** [comment]
@Kikobeats That sounds like an awesome and ambitious project. I hope you've come up with an elegant solution.

Just off the top of my head I was thinking you could wrap the 'whole' page in a `<Swipeable />` component do get the events captured you're looking for. 

After that you'll know if the event was a `swipedRight` or `swipeLeft`, then somehow determine if the touch event was started in one of your 'boxes' and if it was swiped far enough. 😬 lol

Sounds like a fun project. If you're able to share the code I'd love to see the solution you come up with. Hope this helped. Good luck sir!😀

**Comment by hartzis** [comment]
Any updates to report on solutions here? Hope you got it figured out.

**Comment by Kikobeats** [comment]
Hey!

I finally implemented this using a state component:

https://github.com/windtoday/windtoday-marketplace/blob/cee3515ee1dc64fbb8645bdad79b94f05bdb14b4/src/app/Main/index.js#L35-L36

and works fine! Thanks for your time 😄

**Comment by hartzis** [comment]
@Kikobeats sweet solution, that's awesome!

I checked out the app, windtoday.co, very slick! nice job!

**Comment by Kikobeats** [comment]
@hartzis oh, thanks! trying to improve it every day 😄
