### ISSUE TITLE
Unmet peer dependency: Swipeable needs older version of React

### ISSUE THREAD

**Issue by git4t3ch** [dogfessional/react-swipeable#63]
I have a project with installed `React@15.4.1`

Now I want to add this package, but this error appears:

```
-- UNMET PERR DEPENDENCY react@>=0.12.0 || ^15.0.0-0
npm WARN react-swipeable@3.9.2 requires a peer of react@>=0.12.0 || ^15.0.0-0
but none was installed
```
If I understand right, this package has React from `0.12` to `15.0` versions in its peer dependencies list, but my project uses higher version and that's why I can't add this package to my project. So what is possible solution?

Please help

**Comment by hartzis** [comment]
@git4t3ch what node and/or npm/yarn version are you using?

npm should be fine with that peer dep for `react@15.4.1`

I checked [https://semver.npmjs.com/](https://semver.npmjs.com/) and put in package:`react` and range:`>=0.12.0 || ^15.0.0-0` and `15.4.1` is highlighted.

**Comment by hartzis** [comment]
@git4t3ch Found precedent that this is most likely another package in your dependencies throwing this warning, but sadly npm prints all deps even though `15.4.1` is correctly fulfilled by `^15.0.0-0`

please checkout this reference:
https://github.com/reactjs/react-redux/pull/342#issuecomment-207647767
