### ISSUE TITLE
React 15.5 and 16 deprecation warnings

### ISSUE THREAD

**Issue by MikeLP** [dogfessional/react-swipeable#65]
Here is deprecation warning.
`Warning: Swipeable: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`
So any plans to refactor PropTypes and createClass before new React version coming?

**Comment by hartzis** [comment]
nice warning, I wanted to combo `extend React.Component` and HOC capabilities to a major version release soon. i may try to get this out in the next couple of weeks. 

Looks like we already got a PR for the warning, #64 , woo!

If someone is willing/wanting to take a stab at HOC via something like #36 please let me know you're attempting so I don't start the work.

**Comment by hartzis** [comment]
Will close when all issues in #66 and #67 pr is merged in, and major version v4 released since we have to drop support for react v12 & v13.

**Comment by serheyShmyg** [comment]
@hartzis It's a bad idea remove createClass and propTypes in major version.
Warnings can be fixed as minor version release.

**Comment by hartzis** [comment]
@serheyShmyg I've done a bunch of research and asked a few other open source maintainers and the consensus seems to be when you drop support, ala removing react v12 and v13 from peer-deps, that requires a major bump.

I too was hoping to avoid the major bump.

Example of major due partially to dropping support:
https://github.com/reactjs/react-redux/releases/tag/v4.0.0

I'm also proposing a major change anyways, #69

**Comment by hartzis** [comment]
fixed with v4, just published
