### ISSUE TITLE
Synchronize npm with github versions

### ISSUE THREAD

**Issue by jcperez-ch** [dogfessional/react-swipeable#68]
I went to the releases list and the latest found there is [`3.6.0`](https://github.com/dogfessional/react-swipeable/releases).  Then I realized my project had `3.9.2` installed and got confused, so I verified in [npm](https://www.npmjs.com/package/react-swipeable) and saw the current version.

It would be good idea to synchronize the release lists with the CHANGELOG.md and also include notes for every minor version if possible.

Probably what I want is not priority, but I still wanted to rise my hand.

**Comment by hartzis** [comment]
yeah.. it got out of sync a while ago, wish i could just tell it to use the changelog.md since that is upto date

**Comment by hartzis** [comment]
well trying to do retro active tagging is not easy and annoying lol

v4 is coming out soon and i'll be sure to attempt to stay on top of it from there

**Comment by jcperez-ch** [comment]
Yeah, it's annoying.  I guess v4 will come before react16 so, looking forward to it.  Thanks
