### ISSUE TITLE
Publish newer version with 'prop-types' changes

### ISSUE THREAD

**Issue by nikuda** [dogfessional/react-swipeable#71]
Is there anything holding back a new release? Would be good to get the PropTypes changes (https://github.com/dogfessional/react-swipeable/commit/c52c66fd867b96fe1c6a0a19ea8be242fe753010) into npm.

**Comment by hartzis** [comment]
was hoping to get some feedback on a few things, and finding the time to merge in PRs, test, tag, publish.  should be later this week with v4

tracking in #66

**Comment by nikuda** [comment]
Great thank you!
