### ISSUE TITLE
Avoids Date.now() In Its Own Scripts

### ISSUE THREAD

**Issue by ArekRado** [dogfessional/react-swipeable#73]
[Avoids Date.now() In Its Own Scripts](https://developers.google.com/web/tools/lighthouse/audits/date-now)

instead `Date.now()` try `new Date().getTime()`

**Comment by hartzis** [comment]
@ArekRado appreciate the feedback and issue discussion, but after reading that article and doing some research `Date.now()` seems to currently be the most logical choice at this time.

* `Date.now` is accurate enough for `react-swipeable`'s needs and is just a simple method call on the `Date` object
* `new Date().getTime()` requires "too many" resources as it creates a new `Date` object instance allocating more memory, and requires more garbage collection
* `performance.now()`, as that article suggests, doesn't currently have the best [browser support](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) and seems overly accurate for what is currently needed
