### ISSUE TITLE
Disable/Enable swiper

### ISSUE THREAD

**Issue by anahitsk12** [dogfessional/react-swipeable#76]
Hi there,

how can I progrommatically enable/disable swiper.
DtopPropogation and preventDefaultTouchmoveEvent don't seem to work.

**Comment by hartzis** [comment]
I don't exactly know what you're asking, but maybe this section can help?
https://github.com/dogfessional/react-swipeable#chrome-56-and-later-warning-with-preventdefault

if you add `style={{touchAction: 'none'}}` to the `<Swipeable>` component it disables all native touch and scroll functionality.

**Comment by hartzis** [comment]
We could probably introduce a `disable` or `disableSwipe` prop that can enable/disable the swiper.

**Comment by hartzis** [comment]
Solved with #83 and the new `disabled` prop
