### ISSUE TITLE
ref doesn't work on <swipeable>

### ISSUE THREAD

**Issue by DrBoria** [dogfessional/react-swipeable#77]
Can't use ref on swipeable container. Ref links not to dom node, but on swipeable component.

**Comment by hartzis** [comment]
@DrBoria nice find and thank you for creating an issue. I'm surprised this is the first time someone has mentioned and asked for `ref`'s. This is definitely doable!

We have a few options:
- use a prop like `innerRef` like `style-components` and `formsy-react` do?
  - https://github.com/styled-components/styled-components/pull/122
  - https://github.com/christianalfoni/formsy-react/blob/master/src/HOC.js#L30
  - `<Swipeable innerRef={(el) => this.swipeableElement = el} >`
- "create our own" prop to get ref, something like `swipeableRef`? - [react-docs/refs](https://facebook.github.io/react/docs/refs-and-the-dom.html#exposing-dom-refs-to-parent-components)
  - `<Swipeable swipeableRef={(el) => this.swipeableElement = el} >`

Essentially there is no way currently to just do `<Swipeable ref={(el) => this.el = el} >`, it appears as though we need to create prop that takes a callback that provides the ref element.

We just need to decide on what to name it, currently leaning towards `innerRef`. Thoughts?

Great reference to follow the over arching issue with ref's and HOC's - https://github.com/facebook/react/issues/4213

**Comment by DrBoria** [comment]
Cool thanks)
Nice work!

**Comment by xxxzeus** [comment]
I was using the `useSwipeable()` method, and the ref was working if I mentioned the `ref` prop after the handlers spread in the component but it stopped detecting swipe in touch devices. I got everything to work normally with this workaround:
```jsx
const handlers = useSwipeable({ ... });
const myRef = React.useRef();

<div {...handlers} ref={(t) => {
  handlers.ref(t); // calling halders ref for touch devices
  myRef.current = t; // setting our ref
}}>
```
*Note*: The `ref` prop has to be mentioned after `{...handlers}` else this won't work.

**Comment by hartzis** [comment]
@xxxzeus nice! that's the same approach i tried to communicate here too.
- https://github.com/FormidableLabs/react-swipeable/issues/189#issuecomment-656302682

We'll try to make this a bit more obvious and document it well in `v6`.
