### ISSUE TITLE
deltaX is always positive, regardless of swipe direction

### ISSUE THREAD

**Issue by cwgorman** [dogfessional/react-swipeable#80]
`deltaY` seems to be positive/negative depending on whether it was up or down, but X is always positive.

**Comment by hartzis** [comment]
The docs are not the clearest but `onSwipingUp`, `onSwipingRight`, `onSwipingDown`, `onSwipingLeft` are all fired with `(event, absolute(x/y)`. And `onSwiping` is constantly fired with `(event, deltaX, deltaY, absX, absY, velocity)`.

I just double checked the output from the (demo)[http://dogfessional.github.io/react-swipeable/] and I was getting positive and negative values for `deltaX` with `onSwiping`.

The code also shows `onSwipingLeft` and `onSwipingRight` returning the absolute values.
- `onSwipingLeft` https://github.com/dogfessional/react-swipeable/blob/master/src/Swipeable.js#L133
- `onSwipingRight` https://github.com/dogfessional/react-swipeable/blob/master/src/Swipeable.js#L137

Could you possibly create a jsfiddle and/or demo or gif showing and example output you're seeing?

**Comment by cwgorman** [comment]
Thank you for your reply.

I guess I misunderstood that the directional ones were always absolute. I was attaching the same handler to both `onSwipingLeft` and `onSwipingRight` (I don't want to do anything for up/down, and I wanted to still take advantage of the minimum `delta` for left/right), expecting to be able to distinguish the direction by positive/negative. That's fine though; easy enough to deal with.

Also, I played with the demo, and from the console output, it looks like going left is positive, and going right is negative? Is that expected?

**Comment by cwgorman** [comment]
It looks like `onSwipedLeft` and `onSwipedRight` are signed.

**Comment by hartzis** [comment]
@cwgorman yes, the `delta` is returned, args: `(e, pos.deltaX, isFlick)`.

I would like to eventually return an object with properties to callbacks to remove the arbitrary order of returned values/properties, maybe `v5`, lol.

like this so you can destructure where you use the properties:
```
class SwipeComponent extends React.Component {

  swiped({ event, deltaX, deltaY, isFlick, velocity }) {
    console.log("You Swiped...", event, deltaX, deltaY, isFlick, velocity)
  }

  render() {
    return (
      <Swipeable
        onSwiped={this.swiped} >
          You can swipe here!
      </Swipeable>
    )
  }
}
```
