### ISSUE TITLE
setup innerRef prop

### ISSUE THREAD

**Issue by hartzis** [dogfessional/react-swipeable#81]
use a prop called `innerRef` like style-components and formsy-react do:
- styled-components/styled-components#122
- https://github.com/christianalfoni/formsy-react/blob/master/src/HOC.js#L30

`<Swipeable innerRef={(el) => this.swipeableElement = el} >`

related to issue #77 

solved when PR #82 gets merged and released

**Comment by DrBoria** [comment]
Unknown prop `innerRef` on <div> tag.
Returns after innerRef assignment to swipeable.
I tried using your example and plain string assignment - no success.

**Comment by hartzis** [comment]
this is currently still open and the PR #82 hasn't been merged and released.

were you trying with that PR branch?

I should have PR #82 merged in and released to npm this week! 😄

**Comment by kelly-tock** [comment]
what would you think about migrating to `forwardRef` instead?  it's a little easier to use.

**Comment by hartzis** [comment]
@kelly-tock hey. This issue has been closed a while. Is there an issue you're running into specifically?

As an aside, I'm thinking about dropping the component, <Swipeable>, for the next major release and just providing a hook.

**Comment by kelly-tock** [comment]
No issue specifically, I have it working It’s just the now preferred way for refs like inner ref. Please don’t drop the component I think it’s great to provide both.

**Comment by hartzis** [comment]
I genuinely appreciate the feedback. It is annoyingly hard to get any positive and constructive feedback in the open source world usually.

I think we could probably keep the component but just do a lighter version maybe that just uses the hook internally.

something simple like this:
```
export const Swipeable = ({ children, ...props) => {
  const handlers = useSwipeable(props);
  return <div {...handlers}>{children}</div>
}
```

**Comment by hartzis** [comment]
^ i immediately think that this could just be referenced as a straightforward example though and does not need to be bundled with the package...? 🤔

**Comment by kelly-tock** [comment]
I would just bundle it for convenience. I think the community will be split for a while but appreciate you wanting to move towards hooks!
