### ISSUE TITLE
deltaY is given false or true as a result ! 

### ISSUE THREAD

**Issue by SimoMazil** [dogfessional/react-swipeable#84]
deltaY is given false or true as a result ! is that what it is ? 

I thought deltaY means the Y position of the mouse or touch when you swipe right or left !

any idea how can I get the Y position when I swiped to right or left

**Comment by hartzis** [comment]
@SimoMazil which callback prop(s) are you trying to use?

`onSwiped` should be and is returning `deltaY` in the the [demo](http://dogfessional.github.io/react-swipeable/) the `onSwiped` callback prop outputs the following when the user has 'swiped'
<img width="370" alt="screen shot 2017-07-25 at 2 20 31 pm" src="https://user-images.githubusercontent.com/5378707/28591926-9a7804ae-7144-11e7-9fd3-7709d1838435.png">
the args are `(event, pos.deltaX, pos.deltaY, isFlick, pos.velocity)`, happens here:
https://github.com/dogfessional/react-swipeable/blob/master/src/Swipeable.js#L174

I think the boolean you're refering too is the `isFlick` arg which is an old argument that has been carried over for backwards compatibility but i don't know if it is used that often.

**Comment by hartzis** [comment]
I would like to eventually return an object with properties to callbacks like `onSwiped`, maybe `v5`, lol.

like this so you can destructure where you use the properties:
```
class SwipeComponent extends React.Component {

  swiped({ event, deltaX, deltaY, isFlick, velocity }) {
    console.log("You Swiped...", event, deltaX, deltaY, isFlick, velocity)
  }

  render() {
    return (
      <Swipeable
        onSwiped={this.swiped} >
          You can swipe here!
      </Swipeable>
    )
  }
}
```
