### ISSUE TITLE
Create sample examples

### ISSUE THREAD

**Issue by hartzis** [dogfessional/react-swipeable#85]
setup some codepens?
- simple carousel
- swipe tracking dot
  - two boxes next to each other
  - swipe in right box and see dot/slash move/happen in left box?

**Comment by hartzis** [comment]
started a codepen example:
- https://codepen.io/hartzis/pen/oebBPp

**Comment by joebien** [comment]
Can you tell me what the velocity value represents? I expected it to be the velocity of my finger gliding along the screen, but the values generated don't seem to be giving any predictable pattern. I'm getting -50 to 50 swiping at the same speed. Am I missing something? Thanks for any help.

**Comment by hartzis** [comment]
@joebien thanks for the question, it's been a while since i've messed with that code, so always nice to refresh. `velocity` is essentially `distance / time` and specifically with `react-swipeable` it is `(absolute distance from swipe start) / milliseconds since swipe start`. 

The `distance(∆)` in `pixels` is calculated finding total distance traveled in pixels from where the swipe started using the `Pythagorean Theorem`: `delta = √(abs(∆X)² + abs(∆Y)²)`, [here in the code](https://github.com/dogfessional/react-swipeable/blob/master/src/Swipeable.js#L37) and the `ms(milliseconds)` are calculated using `Date.now()`.

So `velocity` in `react-swipeable` ends of being distance in pixels from where the swipe started divided by the time in milliseconds that have happened while swiping.

The value of `velocity` should always be positive. If you could show me a fiddle/codepen/code example and/or gif/screenshot logging the velocity as negative, and what browser you're using that would be awesome?

In the console output for the [example](http://dogfessional.github.io/react-swipeable/), I'm getting positive values for `velocity` with `onSwiping` and `onSwiped`.

**Comment by hartzis** [comment]
added a simple carousel example with #86, would still like to add more later
