### ISSUE TITLE
Prop onFlick not fired

### ISSUE THREAD

**Issue by moret** [dogfessional/react-swipeable#9]
Hi! I've noticed that onFlick was not being fired. Looking at https://github.com/dogfessional/react-swipeable/blob/master/jsx/Swipeable.jsx code I could not find any reference to props.onFlick.

**Comment by goatslacker** [comment]
Oops, docs need to be updated: c3d5d56ed6f2ff181f05bf9ee1044fc6e9dc7b47

**Comment by moret** [comment]
Or that. 8) Sure, it's functionality is completely covered by onSwiped. Your choice! 8)

**Comment by goatslacker** [comment]
Lets remove from docs so there aren't two overlapping handlers.

Use case:

sometimes all you want to do is handle swipes but the user flicks.

**Comment by hartzis** [comment]
Nice catch @moret , this looks good, closing ticket.
