### ISSUE TITLE
Chrome won't preventDefault

### ISSUE THREAD

**Issue by airandfingers** [dogfessional/react-swipeable#91]
Hi, I'm trying to make it so that swiping within my Swipeable doesn't also scroll the page.

Chrome shows this warning whenever I swipe within my Swipeable:

```
SyntheticEvent.js?66c3:115 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
preventDefault                        @	SyntheticEvent.js?66c3:115
touchMove                             @	Swipeable.js?3aa8:124
ReactErrorUtils.invokeGuardedCallback @	ReactErrorUtils.js?6b31:70
executeDispatch                       @	EventPluginUtils.js?0958:87
executeDispatchesInOrder              @	EventPluginUtils.js?0958:110
executeDispatchesAndRelease           @	EventPluginHub.js?c6b1:42
executeDispatchesAndReleaseTopLevel   @	EventPluginHub.js?c6b1:53
forEachAccumulated                    @	forEachAccumulated.js?b898:24
processEventQueue                     @	EventPluginHub.js?c6b1:215
runEventQueueInBatch                  @	ReactEventEmitterMixin.js?8a20:18
handleTopLevel                        @	ReactEventEmitterMixin.js?8a20:29
handleTopLevelImpl                    @	ReactEventListener.js?2365:73
perform                               @	Transaction.js?6dff:136
batchedUpdates                        @	ReactDefaultBatchingStrategy.js?ef70:63
batchedUpdates                        @	ReactUpdates.js?ce09:98
dispatchEvent                         @	ReactEventListener.js?2365:150
```

The odd thing is, I get this warning even if I don't set `stopPropagation` or `preventDefaultTouchmoveEvent` or call `e.preventDefault` or `e.stopPropagation` myself. It's definitely the Swipeable, though - if I remove the Swipeable entirely, then I no longer see these warnings.

Based on [the link](https://www.chromestatus.com/features/5093566007214080) from that warning, as of January Chrome no longer allows document-level event listeners to prevent defaults. Swipeable seems to use document-level listeners for its mousemove and mouseup events, though it looks like it shouldn't be calling `preventDefault` if the corresponding props aren't set.

Tested on OSX Chrome 62.

**Comment by hartzis** [comment]
Hey @airandfingers , we attempted to fix this with the (last release)[https://github.com/dogfessional/react-swipeable/blob/master/CHANGELOG.md#420].

Can you verify for me what version of `swipeable` and what version of `react` you are using please?

**Comment by airandfingers** [comment]
I was using:

    $ cat node_modules/react-swipeable/package.json | grep version
      "version": "3.9.2"

    $ cat node_modules/react/package.json | grep version
      "version": "15.6.2"

However, I just upgraded to:

    $ cat node_modules/react-swipeable/package.json | grep version
      "version": "4.2.0"

    $ cat node_modules/react/package.json | grep version
      "version": "16.2.0"

And I still see this issue and warning. However, I get a bunch of errors/warnings about versions when I `npm i`, so maybe I just need to bite the bullet and upgrade all my packages to the latest and greatest:

    $ npm i
    +-- UNMET PEER DEPENDENCY react@16.2.0 invalid
    `-- react-swipeable@4.2.0 invalid
      `-- detect-passive-events@1.0.4

    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
    npm WARN redbox-react@1.2.10 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
    npm WARN react-burger-menu@1.9.8 requires a peer of react@>=0.14.0 <16.0.0 but none was installed.
    npm WARN react-dom@15.2.1 requires a peer of react@^15.2.1 but none was installed.
    npm WARN react-redux@4.4.5 requires a peer of react@^0.14.0 || ^15.0.0-0 but none was installed.
    npm WARN react-router@2.5.2 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.

Here's how I'm initializing Swipeable:

        <Swipeable
          onSwiping={this.handleSwiping.bind(this)}
          onSwipedUp={this.handleSwipe.bind(this, 'up') }
          onSwipedRight={this.handleSwipe.bind(this, 'right') }
          onSwipedDown={this.handleSwipe.bind(this, 'down') }
          onSwipedLeft={this.handleSwipe.bind(this, 'left') }
          stopPropagation={true}
          preventDefaultTouchmoveEvent={true}
          >

**Comment by hartzis** [comment]
@airandfingers any updates after bumping versions and re-building?

your usage above of `<Swipeable>` looks great.

my last question, if none of the above worked, is what browser and version are you using to test that is still giving the warning?

Because I can run the [example](http://dogfessional.github.io/react-swipeable/) with `Chrome Version 63` on mac os and I do not see the warning. The example is running `react 16` and `swipeable 4.2.0`.

**Comment by hartzis** [comment]
closing for now, but please re-open if needed 😺
