### ISSUE TITLE
Events when touch starts and ends

### ISSUE THREAD

**Issue by movingobjects** [dogfessional/react-swipeable#92]
It doesn't seem that `onTouchStart` or `onTouchEnd` fire on a Swipeable component--is this right?

How, then, can I know when a touch starts or ends? Is it only possible to receive the swiping events after having dragged beyond the delta value?

**Comment by hartzis** [comment]
you're correct, `swipeable` does not accept `onTouchStart` or `onTouchEnd`.

you're also right that you can know when a "swipe" has started with `onSwiping` when the "swipe" has [passed the `delta`](https://github.com/dogfessional/react-swipeable/blob/master/src/Swipeable.js#L173), and get a "swipe end" with `onSwiped`, again as long as it exceeded the `delta`

what's your use case, just curious?

**Comment by sccottt** [comment]
Thanks for the response!

The use case is for giving audio feedback and showing a "pressed down" state on the component.

**Comment by hartzis** [comment]
so showing a "pressed down" state while also wanting to track "swipes"?

hmmm, i'd maybe just wrap `<Swipeable>` in another `<div onTouchStart={()=>{}}>` or wrap `<Swipeable>`'s children with another `<div onTouchStart={()=>{}}>`?

also open to a pr that explores the possibilities of adding `onTouchStart` and `onTouchEnd` callbacks 😄

**Comment by sccottt** [comment]
I ended up writing a custom component that worked a little more specifically to the project I'm on, which uses more of a *drag and throw* interaction than *swipe*.

I haven't taken a deep dive into the code yet, but would adding `onTouchStart` and `onTouchEnd` just be a matter of calling those function props directly, like is happening with `onMouseDown`?

https://github.com/dogfessional/react-swipeable/blob/8e20c171434812411e4452e29af013337e16d10d/src/Swipeable.js#L126

I'm down to see if I can get that going and send over a pr. I think it'd be useful if, for instance, you want to use those events to give audio feedback when a user presses down and releases on an interactive element without having to put it all inside another wrapper.

**Comment by hartzis** [comment]
nice! yeah, i do think it is probably that straightforward. cheers!

btw that is the first time i have seen the inline source for a code link in a comment, that is cool!

**Comment by hartzis** [comment]
closing and tracking possible work with https://github.com/dogfessional/react-swipeable/issues/108
