### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by michellomp** [dogfessional/react-swipeable#95]
Hi 
I read a carousel tutorial on medium which use [react-swipeable ](https://medium.com/@incubation.ff/build-your-own-css-carousel-in-react-part-one-86f71f6670ca).
The swipe only works on mobile device, but I notice that  your demo  also work in desktop.
Is it a new feature that you added recently ?

**Comment by hartzis** [comment]
@michellomp Thanks for the link to that article, good example and walkthrough.

We did add desktop/mouse support via `trackMouse` prop, `trackMouse={true}` with [realease v4](https://github.com/dogfessional/react-swipeable/releases/tag/v4.0.0)

**Comment by michellomp** [comment]
Thanks @hartzis everything works fine
