### ISSUE TITLE
Unable to install @types for this package from npm

### ISSUE THREAD

**Issue by iamgraviteja** [dogfessional/react-swipeable#96]
Getting  404 error when I tried `npm i @types/react-swipeable`

> npm ERR! code E404
> npm ERR! 404 Not Found: @types/react-swipeable@latest

**Comment by hartzis** [comment]
this repo doesn't currently have type definitions. That package appears to be published and supported by these maintainers, https://github.com/DefinitelyTyped/DefinitelyTyped.

Pretty neat to see a collection of types hosted and maintained, but I'd check with them about issues with their packages, 😸 

I also just tried `npm i @types/react-swipeable` and was able to get it to install correctly, i'd just try again and/or check that your not trying to pull it down from a private repository possibly?
