### ISSUE TITLE
When window is scrolling swipe event didn't fires

### ISSUE THREAD

**Issue by DrBoria** [dogfessional/react-swipeable#97]
Hi, when I scroll window and while it is scrolling swipe events from swipeable element didn't fires.

**Comment by hartzis** [comment]
Hey @DrBoria was curious if you could possibly give me a little more to go off of? maybe a [codesandbox.io/react-swipeable](https://codesandbox.io/s/qq7759m3lq?module=%2Fsrc%2FCarousel.js) example setup with an explanation of how to replicate the issue?

**Comment by hartzis** [comment]
closing due to lack of more info or example. please re-open if needed 😃
